### ISSUE TITLE
Add uniform and normal distributions

### ISSUE THREAD

**Issue by notgull** [smol-rs/fastrand-contrib#6]
See: https://github.com/smol-rs/fastrand/issues/66

@pnevyk Are you still willing to implement this?

**Comment by pnevyk** [comment]
@notgull I just submitted a PR for normal distribution (#7). And I consider `f{32,64}_range` to be the implementation of uniform distribution.

**Comment by pnevyk** [comment]
Uniform distribution implemented in #2. Normal distribution implemented in #7.
